new branch test
Ivan-1007/git_project pull request #1
Opened 2021-02-27 19:26 UTC by Ivan-1007

2021-02-28 16:30 UTC, OldKisel commented on 1_bulls_and_crows/bulls_and_cows_engine.py
> +    res = {'bull': 0, 'crow': 0}
cow?

2021-03-01 09:45 UTC, OldKisel requested changes

2021-03-01 09:45 UTC, OldKisel commented on 1_bulls_and_crows/bulls_and_cows_engine.py
> +    res = {'bull': 0, 'crow': 0}
int(char) - int будет как valueOf от char или просто код из таблицы символов?

2021-03-01 09:46 UTC, Ivan-1007 commented on 1_bulls_and_crows/bulls_and_cows_engine.py
> +    res = {'bull': 0, 'crow': 0}
value '1' = 1

2021-03-01 11:22 UTC, merged